extends: eslint-config-dmitmel/presets/node
env:
  node: true
  browser: true
parserOptions:
  sourceType: module
plugins:
  - simple-import-sort

settings:
  node:
    tryExtensions: ['.tsx', '.ts', '.jsx', '.js', '.json']
    allowModules:
      - ultimate-crosscode-typedefs
      - crosscode-localization-engine
      - react
      - react-dom

rules:
  func-names: off
  camelcase: off
  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
        - modules
        - dynamicImport
  node/no-unpublished-require: off
  new-cap: off

  sort-imports: off
  simple-import-sort/imports: warn
  simple-import-sort/exports: warn

overrides:
  - files: '**/*.{ts,tsx}'
    extends: eslint-config-dmitmel/presets/typescript-addon

  - files: 'src/**/*.{ts,tsx}'
    extends: eslint-config-dmitmel/rules/typescript/with-type-checking
    parserOptions:
      project: 'tsconfig.json'
    rules:
      '@typescript-eslint/no-use-before-define': off
      '@typescript-eslint/naming-convention': off

  - files: 'src/mod/**/*.js'
    globals:
      sc: true
      ig: true
      ccmod: true
