extends: eslint-config-dmitmel/presets/node
env:
  node: true
  browser: true
parserOptions:
  sourceType: module
plugins:
  - simple-import-sort

settings:
  node:
    tryExtensions: ['.tsx', '.ts', '.jsx', '.js', '.json']
    allowModules:
      - ultimate-crosscode-typedefs
      - crosscode-localization-engine
      - react
      - react-dom

rules:
  func-names: off
  camelcase: off
  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
        - modules
        - dynamicImport
  node/no-unpublished-require: off
  new-cap: off

  sort-imports: off
  simple-import-sort/imports: warn
  simple-import-sort/exports: warn

overrides:
  - files: '**/*.{ts,tsx}'
    extends: eslint-config-dmitmel/presets/typescript-addon

  - files: 'src/**/*.{ts,tsx}'
    extends: eslint-config-dmitmel/rules/typescript/with-type-checking
    parserOptions:
      project: 'tsconfig.json'
    rules:
      '@typescript-eslint/naming-convention':
        # The naming policy is designed in similarity with Rust's one.
        - warn
        - selector: default
          format: [snake_case]
          leadingUnderscore: allowSingleOrDouble
          trailingUnderscore: allowSingleOrDouble

        - selector: variable
          filter: { regex: 'Gui$', match: false }
          format: [snake_case, UPPER_CASE]
          leadingUnderscore: allowSingleOrDouble
          trailingUnderscore: allowSingleOrDouble
        - selector: property
          modifiers: [static]
          format: [snake_case, UPPER_CASE]
          leadingUnderscore: allowSingleOrDouble
          trailingUnderscore: allowSingleOrDouble

        - selector: [typeLike, enumMember]
          format: [PascalCase]
        - selector: variableLike
          filter: { regex: 'Gui$', match: true }
          format: [PascalCase]

        - selector: [variable, parameter]
          modifiers: [destructured]
          format: null
        - selector: property
          modifiers: [requiresQuotes]
          format: null
        - selector: [objectLiteralProperty, objectLiteralMethod]
          format: null

        - selector: method
          filter: 'componentDidMount|componentDidUpdate|componentWillUnmount|toString'
          format: null
        - selector: property
          filter: 'contextType|defaultProps|className'
          format: null

  - files: 'src/mod/**/*.js'
    globals:
      sc: true
      ig: true
      ccmod: true
